### ISSUE TITLE
Bundle JAR contains OpenTracing API, Util, and NOOP

### ISSUE THREAD

**Issue by safris** [wavefrontHQ/wavefront-opentracing-bundle-java#17]
This is causing class loading issues in SpecialAgent.

**Comment by hanwavefront** [comment]
@safris Thanks for filing this. Could you provide a bit more context into the issues you're seeing?

**Comment by safris** [comment]
The bundled JAR is loaded into a separate class loader, whereby the JAR's classes are registered to be isolated from the rest of the runtime. This is necessary for a number of reasons, one of which being the exclusion of tracer classes from instrumentation. The OT API+Util+Noop classes also end up being registered to be isolated, which results in two versions of the same classes. This leads to `LinkageError `s. There is no explicit documentation for implementation of Tracer Plugins, but here's an excerpt for[ Instrumentation Plugins](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#6-packaging):
> If the external Instrumentation Plugin JAR imports any `io.opentracing:opentracing-*` dependencies, the `io.opentracing.contrib:opentracing-tracerresolver`, or any other OpenTracing dependencies that are guaranteed to be provided by SpecialAgent, then these dependencies **MUST BE** excluded in the dependency spec (as shown in the example for OkHttp just above).
> If this is not done, it may lead to `LinkageError` due to the existence of multiple versions of the same class in different class loaders.

**Comment by hanwavefront** [comment]
@safris Closing this now that it has been addressed via https://github.com/wavefrontHQ/wavefront-opentracing-bundle-java/commit/e69927c71e10517db250633b40f1fdf3fe1280ae, which is in release v1.0.  Thanks again.

**Comment by safris** [comment]
Thank you @hanwavefront!
